### ISSUE TITLE
Finished supabase init.I think I got it. This command actually helps: `git config --global url."https://".insteadOf git://`

### ISSUE THREAD

**Issue by Raen111** [zenodo/zenodo-migrator#49]
I think I got it. This command actually helps: `git config --global url."https://".insteadOf git://`

Added to Dockerfile with: `RUN git config --global url."https://".insteadOf git://` and also scripts/setup-npm.sh `git config --global url."https://".insteadOf git://`

_Originally posted by @VlastaAIP in https://github.com/zenodo/zenodo/issues/2382#issuecomment-1257790012_

**Comment by carlinmack** [comment]
This repository is inactive
